### ISSUE TITLE
No midi mappings in Ableton 10

### ISSUE THREAD

**Issue by nriddiford** [teenageengineering/op-1-ableton-live-control-surface#3]
I've followed the instructions, and while I can use the OP-1 as midi input (the keys work) there are no default midi mappings set up. How can I fix this?

**Comment by ckuma** [comment]
@nriddiford there's a fork of this that works with Ableton 10, at https://github.com/pcppcp/op1

**Comment by raveslave** [comment]
closing, also see the live11 fork here: https://github.com/marctdt/op1/tree/op1_live11
