### ISSUE TITLE
Not working in ableton live 10

### ISSUE THREAD

**Issue by iHnR** [teenageengineering/op-1-ableton-live-control-surface#4]
I've heard it should work, but it doesn't for me. It shows up in the list of control surfaces but only if I use the system folder (C:\ProgramData\Ableton\Live 10 Suite\Resources\MIDI Remote Scripts). If I use the user folder (C:\Users\<USERNAME>\AppData\Roaming\Ableton\Live 10.1.30\Preferences\User Remote Scripts) it simply doesn't show up.
Either way, the script doesn't work if I select it either. Others seem to have no problem with live 10 so that's apparently not the issue.

EDIT: I do see the other posted issue. The forked script also does not work.

**Comment by raveslave** [comment]
please try https://github.com/marctdt/op1/tree/op1_live11
