### ISSUE TITLE
Not working in Ableton live 11

### ISSUE THREAD

**Issue by superandrew** [teenageengineering/op-1-ableton-live-control-surface#5]
The Python support in Live 11 has been changed from Python 2 to Python 3. So the scripts aren't working anymore.

**Comment by marctdt** [comment]
@superandrew 
I converted the script to python 3 for live11. I didn't try all the functionality so I am not sure if it's fully functional. 

https://github.com/marctdt/op1/tree/op1_live11

**Comment by DataGreed** [comment]
@marctdt thanks! Gonna give it a try. Please consider making a pull-request, I hope someone in TE can take a look at it.

cc @finnTE @jsiverskog @sinosoidal @bolandross  ;)

**Comment by raveslave** [comment]
hi @marctdt great that you tuned this for live 11 & python 3    
how about we link directly to your repo as ours is an outdated fork of the original work by @sinosoidal made back in 2012 (there was also some great fixed made for live9 @pcppcp that you have in your fork)
if ok with you, please let me know what credits text / info you want us to put in the link

@DataGreed did you have time to test this in live11 (and 10?).

**Comment by raveslave** [comment]
ok, so thanks to Marc, the latest plugin now lives here. we've tested it internally and seem to work fine with live 11!   
👉 https://github.com/marctdt/op-1-ableton-live-control-surface/tree/live-11

big thanks to 
- Nuno Santos (Imaginando, Lda) that did the original Implementation   
- Jozef Henzl (https://github.com/pcppcp) for the live9 patches
- Marc Tran Du Trieu (https://github.com/marctdt) for the new live11 port
